<?php

//
// Copyright 2009 Clemson University
//

require_once "jobs.php";
require_once "mviews.php";
require_once "cvterms.php";
/*************************************************************************
*
*/
function tripal_core_init(){

}
/*************************************************************************
*
*/
function tripal_create_moddir($module_name){
   // make the data directory for this module
   $data_dir = file_directory_path() . "/tripal/$module_name";
   if(!file_check_directory($data_dir,FILE_CREATE_DIRECTORY)){
      $message = "Cannot create directory $data_dir. This module may not ".
                 "behave correctly without this directory.  Please  create ".
                 "the directory manually or fix the problem and reinstall.";
      drupal_set_message($message,'error');      
      watchdog('tripal_core',$message,array(),WATCHDOG_ERROR);
   }
}
/*************************************************************************
*
*/
function tripal_core_menu() {
   $items = array();
   
   // Triapl setting groups
   $items['admin/tripal'] = array(
      'title' => 'Tripal Management',
      'description' => "Manage the behavior or Tripal and its various modules.",
      'position' => 'right',
      'weight' => -5,
      'page callback' => 'system_admin_menu_block_page',
      'access arguments' => array('administer site configuration'),
      'file' => 'system.admin.inc',
      'file path' => drupal_get_path('module', 'system'),
   );

   // the administative settings menu
/*   $items['admin/tripal/tripal_core'] = array(
     'title' => 'Tripal core settings',
     'description' => 'Tripal Settings',
     'page callback' => 'drupal_get_form',
     'page arguments' => array('tripal_core_admin'),
     'access arguments' => array('access administration pages'),
     'type' => MENU_NORMAL_ITEM,
   );
*/
   $items['admin/tripal/tripal_jobs'] = array(
     'title' => 'Jobs',
     'description' => 'Jobs managed by Tripal',
     'page callback' => 'tripal_jobs_report',
     'access arguments' => array('access administration pages'),
     'type' => MENU_NORMAL_ITEM,
   );
   $items['admin/tripal/tripal_mviews'] = array(
     'title' => 'Materialzied Views',
     'description' => 'Materialized views are used to improve speed of large or complex queries.',
     'page callback' => 'tripal_mviews_report',
     'access arguments' => array('access administration pages'),
     'type' => MENU_NORMAL_ITEM,
   );
   $items['admin/tripal/tripal_mviews/new'] = array(
     'title' => 'Create View',
     'description' => 'Materialized views are used to improve speed of large or complex queries.',
     'page callback' => 'drupal_get_form',
     'page arguments' => array('tripal_mviews_form'),
     'access arguments' => array('access administration pages'),
     'type' => MENU_NORMAL_ITEM,
   );
   $items['admin/tripal/tripal_mviews/action/%/%'] = array(
     'title' => 'Create View',
     'description' => 'Materialized views are used to improve speed of large or complex queries.',
     'page callback' => 'tripal_mviews_action',
     'page arguments' => array(4,5),
     'access arguments' => array('access administration pages'),
     'type' => MENU_CALLBACK,
   );
  return $items;
}

/************************************************************************
*
*/
function tripal_core_admin () {


   $form['chado_feature_data_url'] = array (
      '#title'       => t('URL for data files'),
      '#type'        => t('textfield'),
      '#description' => t("This is the base URL location (without a leading forward slash)  for where files (e.g. blast .xml files) related to each feature are stored. All files available for download or parsing that a feature needs for display should be located in this base directory."), 
      '#required'    => TRUE,
      '#default_value' => variable_get('chado_feature_data_url','sites/default/files/data'),
   );
   
   return system_settings_form($form);
}
